<a href="https://colab.research.google.com/github/swatijaiswal10-code/pytorch-tutorial/blob/main/tensor_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

torch.manual_seed(42)
m1 = torch.rand(7,7).to(device)
m2 = torch.rand(1,7).to(device)

print(torch.matmul(m1, m2.T))
print(m1.device)

# 1. Set seeds for both CPU and GPU explicitly
torch.manual_seed(42)
torch.cuda.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. Pass 'device=' inside rand() so it generates directly on the GPU
m1 = torch.rand(7, 7, device=device)
m2 = torch.rand(1, 7, device=device)

print(torch.matmul(m1, m2.T))
print(m1.device)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]], device='cuda:0')
cuda:0
tensor([[1.9656],
        [1.9694],
        [1.4875],
        [1.9972],
        [1.9483],
        [2.3051],
        [2.5913]], device='cuda:0')
cuda:0


In [39]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(1234)
m1 = torch.rand(2, 3).to(device)
m2 = torch.rand(2, 3).to(device)

print(m1)
print(m2)

mul = torch.matmul(m1,m2.T)
max = torch.max(mul)
min = torch.min(mul)

print(mul)
print(max)
print(min)

max_idx = torch.argmax(mul)
min_idx = torch.argmin(mul)
print(max_idx)
print(min_idx)

torch.manual_seed(7)
t1 = torch.rand(1, 1, 1, 10)
print(t1, t1.shape)
t2 = torch.squeeze(t1)
print(t2, t2.shape)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')
tensor(3, device='cuda:0')
tensor(0, device='cuda:0')
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
